# Generated by Django 2.2.1 on 2020-04-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0004_auto_20200409_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='posted',
            field=models.BooleanField(default=False),
        ),
    ]
